/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyBar {}
  interface MyBarAttributes extends StencilHTMLAttributes {}

  interface MyFoo {
    'dummy': string;
    'toggle': boolean;
  }
  interface MyFooAttributes extends StencilHTMLAttributes {
    'dummy'?: string;
    'toggle'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyBar': Components.MyBar;
    'MyFoo': Components.MyFoo;
  }

  interface StencilIntrinsicElements {
    'my-bar': Components.MyBarAttributes;
    'my-foo': Components.MyFooAttributes;
  }


  interface HTMLMyBarElement extends Components.MyBar, HTMLStencilElement {}
  var HTMLMyBarElement: {
    prototype: HTMLMyBarElement;
    new (): HTMLMyBarElement;
  };

  interface HTMLMyFooElement extends Components.MyFoo, HTMLStencilElement {}
  var HTMLMyFooElement: {
    prototype: HTMLMyFooElement;
    new (): HTMLMyFooElement;
  };

  interface HTMLElementTagNameMap {
    'my-bar': HTMLMyBarElement
    'my-foo': HTMLMyFooElement
  }

  interface ElementTagNameMap {
    'my-bar': HTMLMyBarElement;
    'my-foo': HTMLMyFooElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
